# IMPORTANT NOTES
Access Tokens and Refresh TOkens can be generated from within LinkedIn's UI. Refresh tokens have a maximum lifespan of 1 year and need to be re-generated after that.

```
 {"type": "ERROR", "emitted_at": 1660709800970.4841, "error": {"message": "The token used in the request has been revoked by the user", "internal_message": "401 Client Error: Unauthorized for url: https://api.linkedin.com/rest/organizationalEntityFollowerStatistics?q=organizationalEntity&organizationalEntity=urn%3Ali%3Aorganization%3A144135", "stack_trace": "Traceback (most recent call last):\n  File \"/home/enricojr/.pyenv/versions/source-linkedin-marketing/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 114, in read\n    yield from self._read_stream(\n  File \"/home/enricojr/.pyenv/versions/source-linkedin-marketing/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 179, in _read_stream\n    for record in record_iterator:\n  File \"/home/enricojr/.pyenv/versions/source-linkedin-marketing/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 277, in _read_full_refresh\n    for record in records:\n  File \"/home/enricojr/.pyenv/versions/source-linkedin-marketing/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 410, in read_records\n    request_kwargs = self.request_kwargs(stream_state=stream_state, stream_slice=stream_slice, next_page_token=next_page_token)\n  File \"/home/enricojr/.pyenv/versions/source-linkedin-marketing/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 339, in _send_request\n    return backoff_handler(user_backoff_handler)(request, request_kwargs)\n  File \"/home/enricojr/.pyenv/versions/source-linkedin-marketing/lib/python3.9/site-packages/backoff/_sync.py\", line 105, in retry\n    ret = target(*args, **kwargs)\n  File \"/home/enricojr/.pyenv/versions/source-linkedin-marketing/lib/python3.9/site-packages/backoff/_sync.py\", line 105, in retry\n    ret = target(*args, **kwargs)\n  File \"/home/enricojr/.pyenv/versions/source-linkedin-marketing/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 306, in _send\n    raise exc\n  File \"/home/enricojr/.pyenv/versions/source-linkedin-marketing/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 303, in _send\n    response.raise_for_status()\n  File \"/home/enricojr/.pyenv/versions/source-linkedin-marketing/lib/python3.9/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.linkedin.com/rest/organizationalEntityFollowerStatistics?q=organizationalEntity&organizationalEntity=urn%3Ali%3Aorganization%3A144135\n", "failure_type": "system_error"}}}
 ```

- THis link is coming back as invalid; Need to bring it up with support later. https://api.linkedin.com/v2/regions/1158?locale.language=en&locale.country=US
- https://stackoverflow.com/questions/66830621/linkedin-api-the-token-used-in-the-request-has-been-revoked-by-the-user
